[package]
name = "left_utils"
version = "0.1.2"
edition = "2021"
authors = ["left-TTC <leftear1321@gmail.com>"]
description = "web3 domain utils"
license = "MIT OR Apache-2.0"

[dependencies]
anchor-lang = "0.30.1"

[lib]
proc-macro = false
